all_designations:
  - col_city
  - col_mining
  - col_farming
  - col_generator
  - col_hive
  - col_nexus
  - col_industrial
  - col_foundry
  - col_factory
  - col_bureau
  - col_bureau_spiritualist
  - col_bureau_hive
  - col_bureau_machine
  - col_research
  - col_fortress
  - col_capital
  - col_capital_foundry
  - col_capital_factory
  - col_capital_trade
  - col_capital_extraction
  - col_capital_hive
  - col_capital_machine
  - col_habitat_energy
  - col_habitat_trade
  - col_habitat_research
  - col_habitat_mining
  - col_habitat_farming
  - col_habitat_gestalt_farming
  - col_habitat_fortress
  - col_habitat_industrial
  - col_habitat_foundry
  - col_habitat_factory
  - col_habitat_bureau
  - col_habitat_bureau_spiritualist
  - col_habitat_bureau_hive
  - col_habitat_bureau_machine
  - col_ring_research
  - col_ring_farming
  - col_ring_trade
  - col_ring_generator
  - col_ecu_mix
  - col_ecu_industrial
  - col_ecu_foundry
  - col_ecu_factory
  - col_ecu_research
  - col_mac_foundry
  - col_mac_factory
  - col_hiv
  - col_hiv_foundry
  - col_trophy_machine
  - col_fe_capital
  - col_fe_colony
  - col_resort
  - col_pleasure
  - col_penal
  - col_gestation
  - col_pre_ftl_atomic
  - col_pre_ftl_stone
  - col_pre_ftl_bronze
  - col_pre_ftl_early_space
  - col_pre_ftl_industrial
  - col_pre_ftl_iron
  - col_pre_ftl_machine
  - col_pre_ftl_medieval
  - col_pre_ftl_renaissance
  - col_pre_ftl_steam
  - col_infested
  - col_contingency
  - col_slave
  - col_cosmogenesis_world
  - col_nanotech_world
  - col_wilderness_capital
  - col_wilderness_generator
  - col_wilderness_mining
  - col_wilderness_farming
  - col_wilderness_fortress
  - col_wilderness_tech
  - col_wilderness_nest
  - col_wilderness_refinery
  - col_wilderness_forge
  - col_wilderness_unification