destruction_build_list:
  - trigger:
      - bca_can_remove_building_reasearch
    category_filter:
      - research
    building:
      - building_research_lab_1
      - building_research_lab_2
      - building_research_lab_3
      - building_institute
      - building_supercomputer
      - building_shroud_observatory_1
      - building_shroud_observatory_2
      - building_shroud_observatory_3
      - building_archaeostudies_faculty
      - building_vultaum_reality_computer
      - building_physics_lab_1
      - building_physics_lab_2
      - building_physics_lab_3
      - building_biolab_1
      - building_biolab_2
      - building_biolab_3
      - building_engineering_facility_1
      - building_engineering_facility_2
      - building_engineering_facility_3
      - building_ranger_lodge
      - building_research_upkeep_1
      - building_research_efficiency_1
      - building_fe_lab_1
      - building_fe_lab_2
  - trigger:
      - bca_advanced_research_building_replace
    building:
      - building_research_lab_1
      - building_research_lab_2
      - building_research_lab_3
  - trigger:
      - bca_can_remove_building_factory
    category_filter:
      - manufacturing
    building:
      - building_factory_1
      - building_factory_2
      - building_factory_3
      - building_factory_upkeep_1
      - building_factory_efficiency_1
      - building_affluence_emporium
      - building_affluence_center
  - trigger:
      - bca_advanced_factory_building_replace
    building:
      - building_factory_1
      - building_factory_2
      - building_factory_3
  - trigger:
      - bca_can_remove_building_foundry
    category_filter:
      - manufacturing
    building:
      - building_foundry_1
      - building_foundry_2
      - building_foundry_3
      - building_foundry_efficiency_1
      - building_foundry_upkeep_1
      - building_micro_forge
      - building_nano_forge
  - trigger:
      - bca_advanced_foundry_building_replace
    building:
      - building_foundry_1
      - building_foundry_2
      - building_foundry_3
  - trigger:
      - bca_can_remove_building_industry
    category_filter:
      - manufacturing
    building:
      - building_ministry_production
      - building_production_center
      - building_archaeo_refinery
      - building_crystal_plant
      - building_chemical_plant
      - building_refinery
  - trigger:
      - bca_can_remove_building_trade
    category_filter:
      - trade
    building:
      - building_fe_market_1
      - building_fe_market_2
      - building_galactic_stock_exchange
      - building_commercial_megaplex
      - building_commercial_zone
  - trigger:
      - bca_advanced_trade_building_replace
    building:
      - building_commercial_zone
  - trigger:
      - bca_can_remove_pop_assemble
    category_filter:
      - pop_assembly
    building:
      - building_robot_assembly_plant
      - building_robot_assembly_complex
      - building_machine_assembly_plant
      - building_machine_assembly_complex
      - building_clone_vats
      - building_posthumous_employment_center
      - building_spawning_pool
      - building_offspring_nest
  - trigger:
      - bca_can_remove_building_fortress
    category_filter:
      - army
    building:
      - building_dread_encampment
      - building_military_academy
      - building_stronghold
      - building_fe_fortress
  - trigger:
      - bca_can_remove_building_resource
    building:
      - building_hydroponics_farm