jobs_info:
  - type: technician
    resource: energy
    class_regular: worker
    class_gestalt: simple_drone
  - type: miners
    resource: minerals
    class_regular: worker
    class_gestalt: simple_drone
  - type: farmers
    resource: food
    class_regular: worker
    class_gestalt: simple_drone
  - type: metallurgists
    resource: alloys
    class_regular: specialist
    class_gestalt: complex_drone
  - type: artisans
    resource: consumer_goods
    class_regular: specialist
    class_gestalt: complex_drone
  - type: physicists
    resource: physics_research
    class_regular: specialist
    class_gestalt: complex_drone
  - type: biologists
    resource: society_research
    class_regular: specialist
    class_gestalt: complex_drone
  - type: engineers
    resource: engineering_research
    class_regular: specialist
    class_gestalt: complex_drone