overlapping_zones:
- zone_research
- zone_research_engineering
- zone_unity
- zone_unity_spiritualist
- zone_research_society
- zone_unity_bio_trophy
- zone_research_unity
- zone_research_physics
- zone_habitat_research_unity
