secondary_districts_for_zone:
  zone_agrarian_anglers:
  - district_farming
  - district_orchard_forests
  zone_agrarian_urban:
  - district_farming
  - district_orchard_forests
  zone_anglers:
  - district_farming
  - district_orchard_forests
  zone_betharian:
  - district_mining
  - district_melting
  - district_hollow_mountains
  zone_betharian_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_betharian_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_energy:
  - district_generator
  - district_geothermal
  - district_photosynthesis_fields
  - district_hab_energy
  zone_energy_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_energy_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_energy_physics:
  - district_generator
  - district_geothermal
  - district_photosynthesis_fields
  zone_energy_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_energy_wilderness:
  - district_generator
  - district_geothermal
  - district_photosynthesis_fields
  zone_exotic_gases:
  - district_farming
  - district_orchard_forests
  zone_exotic_gases_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_exotic_gases_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_factory_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_factory_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_factory_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_factory_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_food:
  - district_farming
  - district_orchard_forests
  zone_food_biology:
  - district_farming
  - district_orchard_forests
  zone_food_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_food_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_food_wilderness:
  - district_farming
  - district_orchard_forests
  zone_fortress_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_fortress_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_fortress_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_fortress_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_foundry_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_foundry_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_foundry_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_foundry_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_habitat_hydroponics:
  - district_hab_energy
  zone_habitat_research:
  - district_hab_science
  zone_habitat_research_unity:
  - district_hab_science
  zone_industrial_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_industrial_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_industrial_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_industrial_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_minerals:
  - district_mining
  - district_melting
  - district_hollow_mountains
  - district_hab_mining
  zone_minerals_engineering:
  - district_mining
  - district_melting
  - district_hollow_mountains
  zone_minerals_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_minerals_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_minerals_wilderness:
  - district_mining
  - district_melting
  - district_hollow_mountains
  zone_rare_crystals:
  - district_mining
  - district_melting
  - district_hollow_mountains
  zone_rare_crystals_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_rare_crystals_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_research:
  - district_polytechnic
  zone_research_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_research_engineering:
  - district_hab_science
  - district_polytechnic
  zone_research_engineering_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_research_engineering_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_research_engineering_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_research_engineering_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_research_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_research_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_research_physics:
  - district_hab_science
  - district_polytechnic
  zone_research_physics_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_research_physics_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_research_physics_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_research_physics_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_research_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_research_society:
  - district_hab_science
  - district_polytechnic
  zone_research_society_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_research_society_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_research_society_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_research_society_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_research_unity:
  - district_polytechnic
  zone_resort_grand_museum:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_resort_hunting_ground:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_resort_proving_grounds:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_resort_restoration_enclave:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_resort_spiritual_retreat:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_resort_zoo:
  - district_resort_1
  - district_resort_2
  - district_resort_3
  zone_spawning_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_subterranean_urban:
  - district_mining
  - district_melting
  - district_hollow_mountains
  zone_trade_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_trade_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_trade_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_trade_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_unity:
  - district_polytechnic
  zone_unity_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_unity_bio_trophy:
  - district_polytechnic
  zone_unity_bio_trophy_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_unity_bio_trophy_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_unity_bio_trophy_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_unity_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_unity_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_unity_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_unity_spiritualist:
  - district_polytechnic
  zone_unity_spiritualist_arcology:
  - district_arcology_urban_1
  - district_arcology_urban_2
  - district_arcology_urban_3
  zone_unity_spiritualist_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
  zone_unity_spiritualist_ring_world:
  - district_rw_urban_1
  - district_rw_urban_2
  - district_rw_urban_3
  zone_volatile_motes:
  - district_generator
  - district_geothermal
  - district_photosynthesis_fields
  zone_volatile_motes_hive:
  - district_hive_1
  - district_hive_2
  - district_hive_3
  zone_volatile_motes_nexus:
  - district_nexus_1
  - district_nexus_2
  - district_nexus_3
