all_districts:
- district_cosmogenesis_goverment
- district_mindlink
- district_city
- district_resort
- district_resort_1
- district_resort_2
- district_resort_3
- district_prison
- district_slave
- district_hive
- district_hive_1
- district_hive_2
- district_hive_3
- district_nexus
- district_nexus_1
- district_nexus_2
- district_nexus_3
- district_prison_industrial
- district_battle_thrall
- district_srw_commercial
- district_arcology_housing
- district_arcology_leisure
- district_arcology_urban_1
- district_arcology_urban_2
- district_arcology_urban_3
- district_generator
- district_generator_uncapped
- district_mining
- district_mining_uncapped
- district_farming
- district_farming_uncapped
- district_geothermal
- district_melting
- district_polytechnic
- district_hab_housing
- district_hab_energy
- district_hab_mining
- district_hab_science
- district_rw_city
- district_rw_hive
- district_rw_nexus
- district_rw_urban_1
- district_rw_urban_2
- district_rw_urban_3
- district_craglands
- district_photosynthesis_fields
- district_photosynthesis_fields_uncapped
- district_hollow_mountains
- district_hollow_mountains_uncapped
- district_orchard_forests
- district_orchard_forests_uncapped

primary_districts:
- district_mindlink
- district_city
- district_resort
- district_prison
- district_slave
- district_hive
- district_nexus
- district_prison_industrial
- district_battle_thrall
- district_arcology_housing
- district_arcology_leisure
- district_hab_housing
- district_rw_city
- district_rw_hive
- district_rw_nexus
- district_craglands


secondary_districts:
- district_resort_1
- district_resort_2
- district_resort_3
- district_hive_1
- district_hive_2
- district_hive_3
- district_nexus_1
- district_nexus_2
- district_nexus_3
- district_arcology_urban_1
- district_arcology_urban_2
- district_arcology_urban_3
- district_generator
- district_mining
- district_farming
- district_geothermal
- district_melting
- district_polytechnic
- district_hab_energy
- district_hab_mining
- district_hab_science
- district_rw_urban_1
- district_rw_urban_2
- district_rw_urban_3
- district_photosynthesis_fields
- district_hollow_mountains
- district_orchard_forests
#- district_generator_uncapped
#- district_mining_uncapped
#- district_farming_uncapped
#- district_photosynthesis_fields_uncapped
#- district_hollow_mountains_uncapped
#- district_orchard_forests_uncapped

secondary_districts_d1:
- district_resort_1
- district_hive_1
- district_nexus_1
- district_arcology_urban_1
- district_rw_urban_1
- district_generator
- district_geothermal
- district_hab_energy
- district_photosynthesis_fields

secondary_districts_d2:
- district_resort_2
- district_hive_2
- district_nexus_2
- district_arcology_urban_2
- district_rw_urban_2
- district_mining
- district_melting
- district_hab_mining
- district_hollow_mountains

secondary_districts_d3:
- district_resort_3
- district_hive_3
- district_nexus_3
- district_arcology_urban_3
- district_rw_urban_3
- district_farming
- district_polytechnic
- district_hab_science
- district_orchard_forests

zone_slot_district_slot_mapping:
    z3: d1
    z4: d2
    z5: d3