zones_info:
- icon: GFX_district_specialization_urban
  zones:
  - zone_urban
  - zone_subterranean_urban
  - zone_agrarian_anglers
  type: urban
  fitness_trigger:
    always: -200
    bca_is_farming_habitat: 300
- icon: GFX_district_specialization_trade
  zones:
  - zone_trade
  - zone_trade_arcology
  - zone_trade_ring_world
  - zone_trade_nexus
  - zone_trade_hive
  type: trade
  fitness_trigger:
    has_trade_designation: 200
- icon: GFX_district_specialization_industrial
  zones:
  - zone_industrial
  - zone_industrial_arcology
  - zone_industrial_ring_world
  - zone_industrial_nexus
  - zone_industrial_hive
  type: industrial
  fitness_trigger:
    has_industrial_designation: 200
    has_factory_designation: 100
    has_foundry_designation: 100
- icon: GFX_district_specialization_foundry
  zones:
  - zone_foundry
  - zone_foundry_arcology
  - zone_foundry_ring_world
  - zone_foundry_nexus
  - zone_foundry_hive
  type: foundry
  fitness_trigger:
    has_foundry_designation: 200
    has_industrial_designation: 150
    has_factory_designation: 100
- icon: GFX_district_specialization_factory
  zones:
  - zone_factory
  - zone_factory_arcology
  - zone_factory_ring_world
  - zone_factory_nexus
  - zone_factory_hive
  type: factory
  fitness_trigger:
    has_factory_designation: 200
    has_industrial_designation: 150
    has_foundry_designation: 100
- icon: GFX_district_specialization_research
  zones:
  - zone_research
  - zone_habitat_research
  - zone_central_spire
  - zone_research_arcology
  - zone_research_ring_world
  - zone_research_nexus
  - zone_research_hive
  type: research
  fitness_trigger:
    has_research_designation: 200
- icon: GFX_district_specialization_physics
  zones:
  - zone_research_physics
  - zone_minerals_physics
  - zone_research_physics_arcology
  - zone_research_physics_ring_world
  - zone_research_physics_nexus
  - zone_research_physics_hive
  type: physics
  fitness_trigger:
    has_research_designation: 200
- icon: GFX_district_specialization_society
  zones:
  - zone_research_society
  - zone_research_society_arcology
  - zone_research_society_ring_world
  - zone_research_society_nexus
  - zone_research_society_hive
  type: society
  fitness_trigger:
    has_research_designation: 200
- icon: GFX_district_specialization_engineering
  zones:
  - zone_research_engineering
  - zone_research_engineering_arcology
  - zone_research_engineering_ring_world
  - zone_research_engineering_nexus
  - zone_research_engineering_hive
  type: engineering
  fitness_trigger:
    has_research_designation: 200
- icon: GFX_district_specialization_bureaucrat
  zones:
  - zone_research_unity
  - zone_habitat_research_unity
  type: bureaucrat
  fitness_trigger:
    has_unity_designation: 150
    has_research_designation: 150
- icon: GFX_district_specialization_unity
  zones:
  - zone_unity
  - zone_unity_bio_trophy
  - zone_unity_arcology
  - zone_unity_bio_trophy_arcology
  - zone_unity_ring_world
  - zone_unity_bio_trophy_ring_world
  - zone_unity_nexus
  - zone_unity_bio_trophy_nexus
  - zone_unity_hive
  type: unity
  fitness_trigger:
    has_unity_designation: 200
- icon: GFX_district_specialization_priest
  zones:
  - zone_unity_spiritualist
  - zone_resort_spiritual_retreat
  - zone_unity_spiritualist_arcology
  - zone_unity_spiritualist_ring_world
  - zone_unity_spiritualist_nexus
  type: priest
  fitness_trigger:
    has_unity_designation: 200
- icon: GFX_district_specialization_fortress
  zones:
  - zone_fortress
  - zone_fortress_arcology
  - zone_fortress_ring_world
  - zone_fortress_nexus
  - zone_fortress_hive
  type: fortress
  fitness_trigger:
    has_fortress_designation: 200
- icon: GFX_district_specialization_resort
  zones:
  - zone_resort
  type: resort
  fitness:
    col_resort: 200
    col_pleasure: 180
    col_habitat_trade: 80
- icon: GFX_district_specialization_entertainer
  zones:
  - zone_resort_entertainment
  type: entertainer
  fitness:
    col_resort: 180
    col_pleasure: 160
- icon: GFX_district_specialization_zoo
  zones:
  - zone_resort_zoo
  type: zoo
  fitness:
    col_resort: 150
    col_trophy_machine: 120
- icon: GFX_district_specialization_culture_worker
  zones:
  - zone_resort_grand_museum
  type: culture_worker
  fitness:
    col_resort: 150
- icon: GFX_district_specialization_trophy_hunter
  zones:
  - zone_resort_hunting_ground
  type: trophy_hunter
  fitness:
    col_trophy_machine: 180
- icon: GFX_district_specialization_healthcare
  zones:
  - zone_resort_restoration_enclave
  type: healthcare
  fitness:
    col_resort: 120
- icon: GFX_district_specialization_duelist
  zones:
  - zone_resort_proving_grounds
  type: duelist
  fitness:
    col_fortress: 80
    col_resort: 100
- icon: GFX_district_specialization_knight_commander
  zones:
  - zone_habitat_knights
  type: knight_commander
  fitness_trigger:
    always: 50
- icon: GFX_district_specialization_energy
  zones:
  - zone_energy
  - zone_energy_ring_world
  - zone_energy_nexus
  - zone_energy_hive
  type: energy
  fitness_trigger:
    has_generator_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_betharian
  zones:
  - zone_betharian
  - zone_betharian_nexus
  - zone_betharian_hive
  type: betharian
  fitness_trigger:
    has_generator_designation: 300
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_minerals
  zones:
  - zone_minerals
  - zone_minerals_nexus
  - zone_minerals_hive
  type: minerals
  fitness_trigger:
    has_mining_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_food
  zones:
  - zone_food
  - zone_food_ring_world
  - zone_food_hive
  type: food
  fitness_trigger:
    has_farming_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_rare_crystals
  zones:
  - zone_rare_crystals
  - zone_rare_crystals_nexus
  - zone_rare_crystals_hive
  type: rare_crystals
  fitness_trigger:
    has_generator_designation: 120
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_volatile_motes
  zones:
  - zone_volatile_motes
  - zone_volatile_motes_nexus
  - zone_volatile_motes_hive
  type: volatile_motes
  fitness_trigger:
    has_mining_designation: 120
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_exotic_gases
  zones:
  - zone_exotic_gases
  - zone_exotic_gases_nexus
  - zone_exotic_gases_hive
  type: exotic_gases
  fitness_trigger:
    has_farming_designation: 120
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_angler
  zones:
  - zone_anglers
  type: angler
  fitness_trigger:
    has_farming_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_agrarian
  zones:
  - zone_agrarian_urban
  type: agrarian
  fitness_trigger:
    has_farming_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_hydroponics
  zones:
  - zone_habitat_hydroponics
  type: hydroponics
  fitness_trigger:
    has_farming_designation: 200
    bca_in_secondary_selector: 100
- icon: GFX_district_specialization_spawning
  zones:
  - zone_spawning
  - zone_spawning_hive
  type: spawning
  fitness_trigger:
    always: 50
  fitness:
    col_hive: 150
    col_capital_hive: 180
    col_hiv: 160
- icon: GFX_district_specialization_machine_replication
  zones:
  - zone_machine_replication
  type: machine_replication
  fitness_trigger:
    always: 50
- icon: GFX_district_specialization_wilderness_urban
  zones:
  - zone_urban_wilderness
  type: wilderness_urban
  fitness_trigger:
    always: -200
- icon: GFX_district_specialization_wilderness_foundry
  zones:
  - zone_foundry_wilderness
  type: wilderness_foundry
  fitness:
    col_wilderness_forge: 200
    col_wilderness_refinery: 180
    col_wilderness_capital: 120
    col_capital_foundry: 100
- icon: GFX_district_specialization_wilderness_research
  zones:
  - zone_research_wilderness
  type: wilderness_research
  fitness:
    col_wilderness_tech: 200
    col_wilderness_capital: 120
    col_wilderness_unification: 100
- icon: GFX_district_specialization_wilderness_unity
  zones:
  - zone_unity_wilderness
  type: wilderness_unity
  fitness:
    col_wilderness_capital: 200
    col_bureau: 140
    col_wilderness_nest: 120
- icon: GFX_district_specialization_wilderness_spawning
  zones:
  - zone_research_unity_wilderness
  type: wilderness_spawning
  fitness:
    col_wilderness_nest: 200
    col_hive: 150
    col_wilderness_capital: 120
    col_capital_hive: 100
- icon: GFX_district_specialization_wilderness_trade
  zones:
  - zone_trade_wilderness
  type: wilderness_trade
  fitness:
    col_wilderness_capital: 180
    col_city: 140
    col_wilderness_unification: 120
- icon: GFX_district_specialization_wilderness_fortress
  zones:
  - zone_fortress_wilderness
  type: wilderness_fortress
  fitness:
    col_wilderness_fortress: 200
    col_fortress: 150
    col_wilderness_capital: 100
- icon: GFX_district_specialization_wilderness_minerals
  zones:
  - zone_minerals_wilderness
  type: wilderness_minerals
  fitness:
    col_wilderness_mining: 200
    col_mining: 150
    col_wilderness_capital: 100
    col_capital_extraction: 120
- icon: GFX_district_specialization_wilderness_energy
  zones:
  - zone_energy_wilderness
  type: wilderness_energy
  fitness:
    col_wilderness_generator: 200
    col_generator: 150
    col_wilderness_capital: 100
- icon: GFX_district_specialization_wilderness_food
  zones:
  - zone_food_wilderness
  type: wilderness_food
  fitness:
    col_wilderness_farming: 200
    col_farming: 150
    col_wilderness_capital: 100
